version: '3.3'

services:
  arango_db:
    container_name: companies_arango_db
    image:  arangodb:3.4.7
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=passw0rd
    volumes:
      - ~/companies/db:/var/lib/arangodb3
